[package]
name = "zingo-testutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zingoconfig = { path = "../zingoconfig" }
zingolib = { path = "../zingolib" }
zingo-cli = { path = "../zingocli" }
portpicker = "0.1.1"
tempdir = "0.3.7"
json = "0.12.4"

