[package]
name = "zingo-testutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zingoconfig = { path = "../zingoconfig" }
zingolib = { path = "../zingolib" }
zcash_primitives = { workspace = true }
portpicker = "0.1.1"
tempdir = "0.3.7"
json = "0.12.4"
log = "0.4.19"
tokio = "1.28.2"
http = "0.2.4"
tracing = "0.1.37"
