[workspace]
members = [
    "zingolib",
    "zingocli",
    "zingoconfig",
    "zingo-memo",
    "zingo-testutils"
]

[workspace.dependencies]
zcash_address = { git = "https://github.com/zingolabs/librustzcash", rev = "fa67d9a645da55265ebea8cedbb77ff42317c726" }
zcash_client_backend = { git = "https://github.com/zingolabs/librustzcash", rev = "fa67d9a645da55265ebea8cedbb77ff42317c726"  }
zcash_encoding = { git = "https://github.com/zingolabs/librustzcash", rev = "fa67d9a645da55265ebea8cedbb77ff42317c726"  }
zcash_note_encryption = "0.4.0"
zcash_primitives = { git = "https://github.com/zingolabs/librustzcash", features = ["transparent-inputs", "test-dependencies"], rev = "fa67d9a645da55265ebea8cedbb77ff42317c726"  }
zcash_proofs = { git = "https://github.com/zingolabs/librustzcash", features = ["multicore"], rev = "fa67d9a645da55265ebea8cedbb77ff42317c726"  }
orchard = "0.5.0"
tonic-build = "0.7.0"
tempdir = "0.3"
portpicker = "0.1"
incrementalmerkletree = { version = "0.4", features = ["test-dependencies"] }

[profile.release]
debug = false

[patch.crates-io]
incrementalmerkletree = { git = "https://github.com/zcash/incrementalmerkletree", rev = "6d6f3fd4e3bf64ad12775ddf345fd9b503c95e69"  }

[profile.test]
opt-level = 3
debug = false
