[package]
name = "zecwallet-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
rustyline = "5.0.2"
clap = "2.33"
log = "0.4"
log4rs = "0.8.3"
shellwords = "1.0.0"

zecwalletlitelib = { path = "./lib/" }


[profile.release]
debug = false