[workspace]
members = [
    "zingolib",
    "zingocli",
    "zingoconfig",
    "zingo-memo",
    "zingo-testutils"
]
resolver = "2"

[workspace.dependencies]
zcash_address = "0.3"
zcash_client_backend = { git = "https://github.com/zcash/librustzcash.git", branch = "release-lwsdk-2.0.0" }
zcash_encoding = "0.2"
zcash_note_encryption = "0.4"
zcash_primitives = { version = "0.13.0-rc.1" }
zcash_proofs = { version = "0.13.0-rc.1" }
orchard = "0.6"
tonic-build = "0.7"
tempdir = "0.3"
portpicker = "0.1"
incrementalmerkletree = { version = "0.5" }
shardtree = "0.1"
build_utils = { path = "./build_utils" }

[profile.release]
debug = false

[profile.test]
opt-level = 3
debug = false

[patch.crates-io]
zcash_primitives = { git = "https://github.com/zcash/librustzcash.git", branch = "release-lwsdk-2.0.0" }
zcash_address = { git = "https://github.com/zcash/librustzcash.git", branch = "release-lwsdk-2.0.0" }

