[workspace]
members = [
    "zingolib",
    "zingocli",
    "zingoconfig",
    "zingo-memo",
    "zingo-testutils"
]
resolver = "2"

[workspace.dependencies]
zcash_address = "0.3"
zcash_client_backend = { version = "0.10.0-rc.2" }
zcash_encoding = "0.2"
zcash_client_sqlite = { git = "https://github.com/zingolabs/librustzcash", rev = "8e582109cad9af14b461f76429f9f0437e860115"  }
zcash_note_encryption = "0.4"
zcash_primitives = { version = "0.13.0-rc.1", features = ["transparent-inputs", "test-dependencies"] }
zcash_proofs = { git = "https://github.com/zingolabs/librustzcash", features = ["multicore"], rev = "8e582109cad9af14b461f76429f9f0437e860115"  }
orchard = "0.5"
tonic-build = "0.7"
tempdir = "0.3"
portpicker = "0.1"
incrementalmerkletree = { version = "0.5", features = ["test-dependencies"] }
shardtree = { git = "https://github.com/zcash/incrementalmerkletree", rev = "bae25ad89c0c192bee625252d2d419bd56638e48"  }
build_utils = { path = "./build_utils" }

[profile.release]
debug = false

[patch.crates-io]
incrementalmerkletree = { git = "https://github.com/zcash/incrementalmerkletree", rev = "bae25ad89c0c192bee625252d2d419bd56638e48" }
shardtree = { git = "https://github.com/zcash/incrementalmerkletree", rev = "bae25ad89c0c192bee625252d2d419bd56638e48" }

[profile.test]
opt-level = 3
debug = false
