#  The order of the members reflects a dimension of the dependency relation, the first four depend on
#     *  zingolib
#  which depends in turn, on the bottom 3.
#  This doesn't account for all dependency relations, for example, zingocli depends on zingoconfig directly (for now).
[workspace]
members = [
    "zingo-testutils",
    "integration-tests",
    "darkside-tests",
    "zingocli",
    "zingolib",
    "zingoconfig",
    "zingo-testvectors",
    "zingo-netutils",
    "zingo-memo",
]
resolver = "2"

[workspace.dependencies]
clap = "4.4"
sapling-crypto = "0.1.2"
zcash_address = { git = "https://github.com/zingolabs/librustzcash.git", tag = "m18_z317_t" } # git tag -s $(git describe --dirty)
zcash_client_backend = { git = "https://github.com/zingolabs/librustzcash.git", tag = "m18_z317_t", features = ["lightwalletd-tonic", "orchard"] }
zcash_encoding = { git = "https://github.com/zingolabs/librustzcash.git", tag = "m18_z317_t" }
zcash_keys = { git = "https://github.com/zingolabs/librustzcash.git", tag = "m18_z317_t", features = ["orchard"] }
zcash_note_encryption = "0.4"
zcash_primitives = { git = "https://github.com/zingolabs/librustzcash.git", tag = "m18_z317_t" }
zcash_proofs = { git = "https://github.com/zingolabs/librustzcash.git", tag = "m18_z317_t" }
zcash_protocol = { git = "https://github.com/zingolabs/librustzcash.git", tag = "m18_z317_t" }
orchard = "0.7.1"
tonic-build = "0.10"
tempdir = "0.3"
portpicker = "0.1"
incrementalmerkletree = { version = "0.5" }
futures = "0.3.15"
shardtree = "0.2"
build_utils = { path = "./build_utils" }
http = "0.2.4"
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = { version = "0.23", features = ["http2"] }
http-body = "0.4.4"
tonic = {version = "0.10.0", features = ["tls", "tls-roots", "tls-webpki-roots"]}
prost = "0.12.0"
tower = { version = "0.4" }
hex = "0.4"
tokio-rustls = "0.23"

[profile.release]
debug = false

[profile.test]
opt-level = 3
debug = false

[patch.crates-io]
orchard = { git = "https://github.com/zcash/orchard", rev = "e74879dd0ad0918f4ffe0826e03905cd819981bd" }
incrementalmerkletree = { git = "https://github.com/nuttycom/incrementalmerkletree", rev = "fa147c89c6c98a03bba745538f4e68d4eaed5146" }
shardtree = { git = "https://github.com/nuttycom/incrementalmerkletree", rev = "fa147c89c6c98a03bba745538f4e68d4eaed5146" }

