[workspace]
members = [
    "zingolib",
    "zingocli",
    "zingoconfig",
    "zingo-memo",
    "zingo-testutils"
]
resolver = "2"

[workspace.dependencies]
zcash_address = "0.3"
zcash_client_backend = { version = "0.10.0-rc.2" }
zcash_encoding = "0.2"
zcash_client_sqlite = "0.8.0-rc.3"
zcash_note_encryption = "0.4"
zcash_primitives = { version = "0.13.0-rc.1", features = ["transparent-inputs", "test-dependencies"] }
zcash_proofs = { version = "0.13.0-rc.1", features = ["multicore"] }
orchard = "0.6"
tonic-build = "0.7"
tempdir = "0.3"
portpicker = "0.1"
incrementalmerkletree = { version = "0.5", features = ["test-dependencies"] }
shardtree = "0.1"
build_utils = { path = "./build_utils" }

[profile.release]
debug = false

[patch.crates-io]
incrementalmerkletree = { git = "https://github.com/zcash/incrementalmerkletree", rev = "bae25ad89c0c192bee625252d2d419bd56638e48" }
shardtree = { git = "https://github.com/zcash/incrementalmerkletree", rev = "bae25ad89c0c192bee625252d2d419bd56638e48" }

[profile.test]
opt-level = 3
debug = false
