[workspace]
members = [
    "zingolib",
    "zingocli",
    "zingoconfig",
    "zingo-memo",
    "zingo-testutils"
]

[workspace.dependencies]
zcash_address = { git = "https://github.com/zingolabs/librustzcash" }
zcash_client_backend = { git = "https://github.com/zingolabs/librustzcash" }
zcash_encoding = { git = "https://github.com/zingolabs/librustzcash" }
zcash_note_encryption = { git = "https://github.com/zingolabs/librustzcash", features = ["pre-zip-212"] }
zcash_primitives = { git = "https://github.com/zingolabs/librustzcash", features = ["transparent-inputs", "test-dependencies"] }
zcash_proofs = { git = "https://github.com/zingolabs/librustzcash", features = ["multicore"] }
orchard = "0.4.0"
tonic-build = "0.7.0"

[profile.release]
debug = false

[profile.test]
opt-level = 3
debug = false
