[package]
name = "zingo-account"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper-rustls = { workspace = true }
prost = { workspace = true }
zcash_keys = { workspace = true }
secrecy = "0.8.0"
