[package]
name = "zingo-cli"
version = "0.2.0"
edition = "2021"

[dependencies]
rustyline = "11.0.0"
clap = "3.2.20"
log = "0.4.17"
shellwords = "1.1.0"
json = "0.12.4"
http = "0.2.8"
tokio =  { version = "1.24.2", features = ["full"] }

zingolib = { path = "../zingolib/" }
zingoconfig = { path = "../zingoconfig/" }

[dev-dependencies]
env_logger = "0.10.0"
zingolib = { path = "../zingolib/", features = ["integration_test"] }
bech32 = "0.9.0"
portpicker = "0.1.1"
rand = "0.8.5"
hex = "0.3"
tempdir = "0.3.7"
tracing-subscriber = "0.3.15"
itertools = "0.10.5"
bip0039 = "0.10.1"
tracing-test = { version = "0.2.4", features = ["no-env-filter"] }
tracing = "0.1.37"
tracing-log = "0.1.3"
orchard = "0.3.0"
zcash_address = { workspace = true }
zcash_client_backend = { workspace = true }
zcash_primitives = { workspace = true }

[features]
default = ["local_env"]
local_env =[]
