name: CI

on:
  pull_request:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  cargo-checkmate:
    uses: ./.github/workflows/cargo-checkmate.yaml

  reject-trailing-whitespace:
    name: Reject trailing whitespace
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Reject trailing whitespace
        run: ./utils/trailing-whitespace.sh reject

  build-test-artifacts:
    name: Build test artifacts
    runs-on: ubuntu-22.04
    env:
      RUSTFLAGS: -D warnings
    container:
      image: zingodevops/ci-build:002
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Symlink lightwalletd and zcash binaries
        run: ln -s /usr/bin/lightwalletd /usr/bin/zcashd /usr/bin/zcash-cli ./zingocli/regtest/bin/

      - name: Symlink zcash parameters
        run: ln -s /root/.zcash-params /github/home

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Build and archive tests
        run: cargo nextest archive --archive-file nextest-archive.tar.zst

      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: nextest-archive
          path: nextest-archive.tar.zst

  run-tests:
    name: Run tests
    runs-on: ubuntu-22.04
    needs: build-test-artifacts
    env:
      RUSTFLAGS: -D warnings
    container:
      image: zingodevops/ci-build:002
      options: --security-opt seccomp=unconfined
    strategy:
      matrix:
        partition: [1, 2, 3, 4]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Symlink lightwalletd and zcash binaries
        run: ln -s /usr/bin/lightwalletd /usr/bin/zcashd /usr/bin/zcash-cli ./zingocli/regtest/bin/

      - name: Symlink zcash parameters
        run: ln -s /root/.zcash-params /github/home

      - name: Download archive
        uses: actions/download-artifact@v3
        with:
          name: nextest-archive

      - name: Run tests
        run: cargo nextest run --archive-file nextest-archive.tar.zst --partition count:${{ matrix.partition}}/4 --profile ci --all-features --verbose --workspace

  create-timestamp:
    uses: zingolabs/zingo-mobile/.github/workflows/create-timestamp.yaml@dev

  create-cache-key:
    uses: zingolabs/zingo-mobile/.github/workflows/create-cache-key.yaml@dev

  build-android:
    strategy:
      matrix:
        arch: [ x86_64, armeabi-v7a ]
    uses: zingolabs/zingo-mobile/.github/workflows/build.yaml@dev
    needs: create-cache-key
    with:
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
      arch: ${{ matrix.arch }}

  integration-test-android:
    uses: zingolabs/zingo-mobile/.github/workflows/integration-test.yaml@dev
    needs: [ create-timestamp, create-cache-key, build-android ]
    with:
      timestamp: ${{ needs.create-timestamp.outputs.timestamp }}
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
      abi: armeabi-v7a

