name: Rust

on: 
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name:                   Checkout repository
        uses:                   actions/checkout@v2
      - uses:                   actions-rs/toolchain@v1
        with:
          toolchain:            1.60.0
          override:             true
          components:           rustfmt, clippy
      - name: Check formatting of code
        run: cargo fmt --check
      - name:                   Install Tarpaulin 
        uses:                   actions-rs/cargo@v1
        with:
          command:              install
          args:                 cargo-tarpaulin --verbose
      - name:                   Generate code coverage
        run: |
          cargo tarpaulin --verbose --all-features --workspace --timeout 300 --out Xml --avoid-cfg-tarpaulin --skip-clean --ignore-tests
      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v2
        with:
          fail_ci_if_error:     true
          fail_ci_if_warn:      true
