name: Rust

on: [pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name:                   Checkout repository
        uses:                   actions/checkout@v2
      - uses:                   actions-rs/toolchain@v1
        with:
          toolchain:            1.60.0
          override:             true
          components:           rustfmt, clippy
      - name:                   Run keygen
        run:                    ./keygen.sh
      - name: Grab cached files
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo  
      - name: Debug step
        run: /home/runner/.cargo/bin/cargo --version
      - name:                   Install Tarpaulin 
        uses:                   actions-rs/cargo@v1
        with:
          command:              install
          args:                 cargo-tarpaulin --verbose
      - name:                   Generate code coverage
        run: |
          cargo tarpaulin --verbose --all-features --workspace --timeout 300 --out Xml --avoid-cfg-tarpaulin
      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v2
        with:
          fail_ci_if_error:     true
